### ISSUE TITLE
Not an issue, just

### ISSUE THREAD

**Issue by thapakazi** [arbabnazar/ansible-aws-vpc-ha-wordpress#4]
@arbabnazar firstly :bowing_man: 
So you are launching 2 webserber instances in [public_subnets](https://github.com/arbabnazar/ansible-aws-vpc-ha-wordpress/blob/master/aws/tasks/webserver.yml#L55-L56) ?

I am searching for the way to provision the instance launched inside the private subnets  (via some bastion) directly from the localhost (my machine :neckbeard: not ssh over bastion and then fire ansible :see_no_evil:  ). My ssh proxy works fine, but kinda not getting it to work with private ips. 

Any thoughts || any tricks you want to share.
thanks again for supercool yamls :wink:

**Comment by arbabnazar** [comment]
@zerOnepal I normally do this using bastion host:

```
##### Private subnet hosts access through bastion host #####
Host tendo-bastion
  HostName 51.33.22.54
  ForwardAgent yes

Host 10.12.* # Range of my private subnet(s)
  ProxyCommand ssh -q tendo-bastion nc -q0 %h %p
```

Hope that help you

**Comment by thapakazi** [comment]
@arbabnazar thanks :bowing_man: 
Still I wonder :open_mouth: if there is a possibility to get it running from a localhost with ansible.

**Comment by arbabnazar** [comment]
If I am not wrong, you want something like [this](https://rbgeek.wordpress.com/2016/05/15/autoscaling-with-aws-instances-using-ansible-pull/)

**Comment by thapakazi** [comment]
hehe, thanks for that awesome post...

 though its not the thing I was asking, you just gave me one more reason to re-design the auto-scaling playbooks :sun_behind_small_cloud: 

By localhost I mean... i want to run playbook from my own machine :neckbeard: into vpc instances... 
something like this: 

```
[ansibe-playbook dothis_from_my_laptop.yml] ----> [through bastion] ---> [private ips in my vpc]
```

**Comment by arbabnazar** [comment]
@zerOnepal that's what I gave you the idea first. I normally do the same. I run the playbook from my local machine to remote hosts(inside the private subnet) through bastion.

Are you able to ssh to the hosts in private subnet from your local machine?

**Comment by thapakazi** [comment]
yeah I can,
oh you are doing it... nice
Can you share like how ? or ellaborate more if possible

**Comment by arbabnazar** [comment]
Can you please first tell me that how you ssh to your hosts(inside private subnet), so I'll help you

**Comment by thapakazi** [comment]
hmm, I use ip of bastion(inside public subnet of my vpc) with my agents forwarded...and then move into the private ips...
Not sure, how I make ansible aware of this ?

**Comment by arbabnazar** [comment]
OK. I am supposing that you are using *NIX based system.

create file under you user home directory like this:

```
vi ~/.ssh/config
```

Then add these contents inside it:

```
##### Private subnet hosts access through bastion host #####
Host tendo-bastion
  HostName 51.33.22.54
  ForwardAgent yes

Host 10.12.* # Range of my private subnet(s)
  ProxyCommand ssh -q tendo-bastion nc -q0 %h %p
```

You just need to change two things in above mentioned contents:
- Public IP of your Bastion Host
- Range of your private subnet (like I have 10.12.4.x,10.12.5.x etc so I just make it simple by regex 10.12.*)

After that ssh to your host in private subnet:

```
ssh username@private-ip
```

and same with ansible:

```
ansible-playbook -i "private-ip," yourplaybook.yml -u username 
```

Hope you get it

**Comment by thapakazi** [comment]
:bowing_man: I owe you a :coffee: 
![screenshot-20161006-23 54 23](https://cloud.githubusercontent.com/assets/1695906/19164822/3e62f31c-8c21-11e6-9bac-32c2dfdf2421.png)

**Comment by arbabnazar** [comment]
I am happy that it worked for you :)

**Comment by arbabnazar** [comment]
I am happy that it worked for you. Please let me know, If I can help you more. I'll take a coffee with you if I'll come, where you are living but really happy that it worked for you

**Comment by thapakazi** [comment]
its `utc + 5:45` :smile: 
[Nepal](https://goo.gl/maps/rKcHk548Ano) is my home, hope you get some slack time to travel.
or in future, I find your place in this spherical earth

**Comment by arbabnazar** [comment]
I have planned to come to Nepal in few months. Will definitely ping you :-)
